apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: phpmyadmin
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - image: my_phpmyadmin
          name: phpmyadmin
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            # - name: PMA_HOST
            #   value: mysql
            - name: DB_NAME
              value: wordpress
            - name: DB_USER
              value: rooty
            - name: DB_PASS
              value: password
            - name: DB_HOST
              value: mysql
            # - name: DB_USER
            #   value: rooty
            # - name: DB_PASS
            #   value: password
            - name: MYSQL_ROOT_PASSWORD
              value: admin
            - name: MYSQL_ROOT_PASSWORD
              value: password
        # - name: DB_HOST
        #   value: mysql
        # - name: DB_NAME
        #   value: wordpress
        # - name: DB_USER
        #   value: root
        # - name: DB_PASS
        #   value: password