apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared-ip
  creationTimestamp: null
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: phpmyadmin
  # externalTrafficPolicy: Cluster
  # loadBalancerIP: 192.168.99.201
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - image: my_phpmyadmin
          name: phpmyadmin
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: PMA_HOST
              value: mysql
            - name: PMA_PORT
              value: "3306"



        # username: mysql
        # password: password