# apiVersion: v1
# kind: Secret
# metadata:
#   labels:
#     app: mysql
#   name: mysql-secret
# type: Opaque
# stringData:
#   MYSQL_DB_NAME: wordpress
#   MYSQL_USER: rooty
#   MYSQL_PASSWORD: password
#   password: admin
#   MYSQL_DB_HOST: mysql-svc
#   MYSQL_HOME: /etc/
# ---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: mysql
  labels:
    app: mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    app: mysql
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        tier: mysql
    spec:
      containers:
      - image: my_mysql
        name: mysql
        # or the otherway around aboce
        imagePullPolicy: Never
        # envFrom:
        #   - secretRef:
        #       name: mysql-secret
        env:
        # - name: MYSQL_ROOT_PASSWORD
        #   value: admin
        - name: DB_NAME
          value: wordpress
        - name: DB_USER
          value: mysql
        - name: DB_PASS
          value: password
        - name: MYSQL_HOME
          value: "/etc/"
        # ports:
        # - containerPort: 3306
        #   name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
