apiVersion: v1

kind: ConfigMap
metadata:
  name: telegraf-config
data:
  telegraf.conf: |+
    ###############################################################################
    #                            INPUT  PLUGINS                                   #
    ###############################################################################
    [[inputs.docker]]
      endpoint = "unix:///var/run/docker.sock"
  
      gather_services = false

      container_names = []

      timeout = "20s"

      docker_label_include = []
      docker_label_exclude = []

      perdevice = true

      total = false

    ###############################################################################
    #                            OUTPUT PLUGINS                                   #
    ###############################################################################
      # Output Plugin InfluxDB
      [[outputs.influxdb]]
        urls = ["$INFLUXDB_URL"]
        skip_database_creation = false
        database = "$INFLUXDB_DB"
        username = "$INFLUXDB_USER"
        password = "$INFLUXDB_USER_PASSWORD"
---
apiVersion: v1
kind: Secret
metadata:
  name: telegraf-secrets
type: Opaque
stringData:
  INFLUXDB_DB: telegraf
  INFLUXDB_URL: http://influxdb:8086
  INFLUXDB_USER: admin
  INFLUXDB_USER_PASSWORD: amber
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: telegraf
  name: telegraf
spec:
  ports:
  - port: 4999
    protocol: TCP
    name: http
  selector:
    app: telegraf-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
        - image: my_telegraf
          name: telegraf
          imagePullPolicy: Never
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-socket
            - mountPath: /etc/telegraf/telegraf.conf
              name: telegraf-config
              subPath: telegraf.conf
              readOnly: true
          envFrom:
            - secretRef:
                name: telegraf-secrets
      volumes:
        - name: telegraf-config
          configMap:
            name: telegraf-config
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock

# Telegraf is a plugin-driven server agent for collecting & reporting metrics
# It is responsible for connecting grafana with Influxdb database