apiVersion: v1
kind: Secret
metadata:
  labels:
    app: grafana
  name: grafana-secret
type: Opaque
stringData:
  password: amber
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: grafana
  labels:
    app: grafana
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: grafana-storage
#   labels:
#     app: grafana
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 20Gi
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - image: my_grafana
        name: grafana
        imagePullPolicy: Never
        ports:
        - name: grafana
          containerPort: 3000
        env:
          - name: GF_SECURITY_ADMIN_USER
            value: admin
          - name: GF_SECURITY_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: grafana-secret
                key: password
        volumeMounts:
        - name: provisioning
          mountPath: /usr/share/grafana/conf/provisioning
      volumes:
      - name: provisioning
        configMap:
          name: grafana-config
          items:
          - key: dashboards.yml
            path: dashboards/dashboards.yml
          - key: datasources.yml
            path: datasources/datasources.yml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  datasources.yml: |
    apiVersion: 1
    datasources:
    - name: InfluxDB
      type: influxdb
      access: proxy
      database: telegraf
      isDefault: true
      user: admin
      password: amber
      url: http://influxdb:8086
  dashboards.yml: |
    apiVersion: 1
    providers:
    - name: 'influxdb'
      orgId: 1
      folder: ''
      folderUid: ''
      type: file
      disableDeletion: false
      editable: true
      updateIntervalSeconds: 10
      allowUiUpdates: true
      options:
        path: /usr/share/grafana/public/dashboards
# to load up in grafana 
# HTTP URL : http://influxdb:8086
# DATABASE : influxdb
# USER : admin 
# PASSWORD : amber