apiVersion: v1
kind: Secret
metadata:
  labels:
    app: grafana
  name: grafana-secret
type: Opaque
stringData:
  password: amber
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  type: LoadBalancer
  ports:
    - port: 3000
  selector:
    app: grafana
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage
  labels:
    app: grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        volumeMounts:
          - mountPath: /data/grafana
            name: grafanaa
        ports:
        - name: grafana
          containerPort: 3000
        env:
          - name: GF_INSTALL_PLUGINS
            value: grafana-piechart-panel, blackmirror1-singlestat-math-panel
          - name: GF_SECURITY_ADMIN_USER
            value: admin
          - name: GF_SECURITY_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: grafana-secret
                key: password
        # volumeMounts:
        #   - mountPath: /var/lib/grafana/dashboards/mysql-dashboard.json
        #     name: grafana-config-volume
        #     readOnly: true
        #     subPath: mysql-dashboard.json
      volumes:
      # - /data/grafana:/var/lib/grafana
      - name: grafana-volume
        hostPath:
          path: /grafana
      - name: grafanaa
        hostPath:
          path: /var/lib/grafana
      # - name: grafana-config-volume
      #   configMap:
      #     name: grafana-config
# to load up in grafana 
# HTTP URL : http://influxdb:8086
# DATABASE : influxdb-database
# USER : admin 
# PASSWORD : amber