apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: ftps
spec:
    selector:
      app: ftps
    type: LoadBalancer
    ports:
    - name: ftp21
      port: 21
      targetPort: 21
    - name: ftp10100
      port: 10100
      targetPort: 10100 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: my_ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 10100
        volumeMounts:
        - name: ftps
          mountPath: /ftp
      volumes:
      - name: ftps
        persistentVolumeClaim:
          claimName: ftps
