# apiVersion: v1
# kind: Secret
# metadata:
#   labels:
#     app: wordpress
#   name: wordpress-secret
# type: Opaque
# stringData:
#   WP_USER: "wp"
#   WP_PASSWORD: "pass"
# ---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 5050
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: my_wordpress
        name: wordpress
        imagePullPolicy: Never
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_NAME
          value: wordpress
        - name: DB_USER
          value: rooty
        - name: DB_PASS
          value: password
        # - name: WORDPRESS_DB_PASSWORD
        #   value: admin

        # - name: WORDPRESS_DB_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: mysql-secret
        #       key: password
        # envFrom:
        #   - secretRef:
        #       name: mysql-secret
        #   - secretRef:
        #       name: wordpress-secret
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
