apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  creationTimestamp: null
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
  - name: wordpress
    port: 5050
    targetPort: 5050
  selector:
    app: wordpress
    tier: frontend
  # externalTrafficPolicy: Cluster
  # loadBalancerIP: 192.168.99.201
  type: LoadBalancer
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: wp-pv-claim
#   labels:
#     app: wordpress
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 20Gi
# ---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: my_wordpress
        name: wordpress
        imagePullPolicy: Never
        env:
        # - name: MYSQL_DB
        #   value: wordpress
        # - name: MYSQL_USER
        #   value: mysql
        # - name: MYSQL_PASS
        #   value: password
        # - name: MYSQL_HOME
        #   value: "/etc/"
        - name: WORDPRESS_DB_HOST
          value: mysql
        ports:
        - containerPort: 5050
          name: wordpress
      #   volumeMounts:
      #   - name: wordpress-persistent-storage
      #     mountPath: /www/wordpress
      # volumes:
      # - name: wordpress-persistent-storage
      #   persistentVolumeClaim:
      #     claimName: wp-pv-claim
# username: ambie
# Password: password